kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: nodejs:latest
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: gameapp
  Project: intrado-game
  Name: game
  Url:
  - Name: dev
    Port: 8080
